### ISSUE TITLE
Friends list in social pane duplicated

### ISSUE THREAD

**Issue by jillkgraves** [Jeremy-Barnes/Critters.NET#107]
After accepting new friend request, friend shows twice in social pane.

Poll for accepted friend requests while polling for online friends

![Screenshot_20220211-231009_Chrome](https://user-images.githubusercontent.com/21324742/153697700-2045b1be-51f4-45d8-ae3a-97f3b2139bf3.jpg)

**Comment by Jeremy-Barnes** [comment]
Oops, duplicate of #122. Mark your issues with BUG and FRONTEND @jillkgraves
