### ISSUE TITLE
Achievements, Bat-Attacks, And Quest Status

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters.NET#15]
Creating this page so that I don't blow up your Discord, and we have a place to record thoughts. The problem statement, as it is affecting me:

NPC 1) Angel
NPC 2) Billy the Bat (https://tvtropes.org/pmwiki/pmwiki.php/Main/GoddamnedBats)

RandomEvent 1) Billy the Bat attacks, taking some random amount of currency from you
RandomEvent 2) Angel says hello
RandomEvent 3) Angel gives you an arbitrary amount of currency
Angel is also an interactable NPC, not just a random event avatar. He has 3 functions when you go to visit him
1) He can heal your pet 1 time per hour
2) He can say hello
   2a) if you have been attacked by Billy within 24 hours, he'll give you a little cash
   2b) If you've visited him before in 7 days, he says something like "Hello again"
HERE'S THE BIG PROBLEM:
Whats the correct way to make Angel know about your bat-attack (or any other event we decide he's interested in, like "healed by Angel", to enforce action 2a)
It has to be persisted somehow
You cant track 100 log ins for achievements unless you've got some kind of record keeping... somewhere
But the form of that is challenging.

**Comment by Jeremy-Barnes** [comment]
There's a lot of variation here, which makes this all tricky to track.

I'm not **necessarily** so interested in a forever-old, hyper-accurate audit log, so we might be able to split across multiple stores.

As a first pass, I'm considering

```
CREATE TABLE user_events(
    user_id int not null foreign key users(user_id),
    event_id int not null,
    event_state text/json/jsonb not null
)
```
https://www.postgresql.org/docs/10/datatype-json.html

This is... permissive. Its also a close cousin to my "store NPC behavior as a script in the DB" solutions.

However, it does allow us a lot of flexibility. Event ID can map to an enum, we can create handlers in the Domain layer.

Suppose we want to track **all** user logins (event_id 1), and we do want a hyper accurate audit log (because you get an achievement for logging in on 13 Friday the 13ths)

Then the event_state object for event_id = 1 looks like

```
{
    "count" : 13,
    "occurrences" : ["3/13/2020 17:07 UTC", "3/14/2020 21:12 UTC", "3/14/2020 23:45 UTC"]
}
```

and the event_state for Billy Attacks (event_id 3) looks like
```
{
"mostRecentOccurrence" : "3/15/2020 01:23 UTC"
}
```

**Comment by Jeremy-Barnes** [comment]
The json blob + code defined event_id also allows us to save data pre-filtered if thats relevant. Perhaps we don't really care to save every single login just to find the Friday the 13 logins, so when I get around to defining that achievement, we define a new event_id  13 and from then on we save relevant user logins in that json blob for event_id = 13
```
{
    "occurrences" : ["3/13/2020 17:07 UTC"]
}
```

Then when the login event is fired via the CNF, it hits the Domain Handler for both Event 1 and Event 13, Event 1 updates its JSON but Event 13 drops it on the floor, because it is currently Wednesday the 24th, and therefore irrelevant.

There are problems with this:
1) It flirts with NoSQL, I like type checks, constraints, etc that come with highly normalized data
2) Pulling a record and updating it will get slow for some types (event 1 here gets big and bad fast), though the jsonb Postgres data type can help with that.
3) Schema is not enforced at all, so if the code changes without migrating the data we're screwed. Perhaps this is moot, because its true of SQL too. We could define interfaces for JSON Blobs, where Event 13 gets its own Interface to hold the JSON to:
```
public interface ILogInFridayThe13th {
    IEnumerable<DateTime> occurrences;
}

This is my first-thought, kneejerk solution. Open to other, better ideas, or tweaks on this. Come at me.

Octopuses are just wet spiders. @maybejosh

**Comment by maybejosh** [comment]
I did a little digging today but couldn't find any decent pattern for handling storage here.

I like the idea of each `event_id` being 1:1 with an interface to kinda cover structure. I don't like the idea of not being able to segregate the different data associated with event types. Like with your "request" type, if we're checking to see if a user has passed 100 logins all that matters is `count` and not the massive `occurrences` list but we'd be getting that as a side-effect.

What about something like
```
CREATE TABLE user_events(
    id int not null,
    user_id int not null foreign key users(user_id),
    event_id int not null,
)

CREATE TABLE user_event_states(
   user_event_id int not null foreign key user_events(id),
   event_state_id int not null,
   event_state text not null
)
```
so `EventId` 1 could be `Login` and `EventStateId` 1 could be `LoginCount` or something to separate out the sub-types of data associated with the event?

**Comment by Jeremy-Barnes** [comment]
I like this pretty good (also I finally have enough mental capacity for hobby programming!?!). I might keep event state as a json data type, because pgsql has built in JSON querying that might be better than loading and parsing the text.
